### ISSUE TITLE
Keyboard Loads on Start

### ISSUE THREAD

**Issue by MichaelRPowell** [XK9274/better-wifi-miyoo#2]
I am not sure if that is intentional, but the keyboard is always on the screen when I start the app. Can this be turned off? It seems the first action anyone would want to do is to navigate the menu before using the keyboard.

The tool has continued to work great, would love to see it as part of the default Onion OS install.

**Comment by XK9274** [comment]
The whole time i've been developing/using this app it hadn't even occurred to me that I forgot to disable this again 😅Thanks for the heads up, fixed in https://github.com/XK9274/better-wifi-miyoo/commit/09fb6e1193ea12cb00cc0041a8108301dc0bc114

PS - it's planned for onion but i think it's targeted sometime between 4.2 and 4.3
